# Generated by Django 2.1.2 on 2021-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210909_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='フリースタイル名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_2',
            field=models.TextField(blank=True, null=True, verbose_name='オーダー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_9',
            field=models.IntegerField(blank=True, choices=[(1, '簡単'), (2, '普通'), (3, '難しい')], null=True, verbose_name='難易度'),
        ),
    ]
